# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_short_2clk/fifo_short_2clk.xci
# IP: The module: 'fifo_short_2clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: ip/fifo_short_2clk/fifo_short_2clk.xci
# IP: The module: 'fifo_short_2clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/f4tnk/dev/LibreSDR_UHD_B220_Mini_FPGA/src/libresdr_b210.gen/fifo_short_2clk/ip/fifo_short_2clk/fifo_short_2clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_short_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
